server:
    port: 4013

management:
    endpoint:
        health:
            show-details: "always"
    endpoints:
        web:
            base-path: /
            exposure:
                include: health, info, prometheus

spring:
    application:
        name: NFDIV Case API
azure:
    application-insights:
        instrumentation-key: ${nfdiv.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

uk:
  gov:
    notify:
       api:
         key: ${nfdiv.uk-gov-notify-api-key:dummy}
         baseUrl: https://api.notifications.service.gov.uk
       email:
         templates:
            english:
              SAVE_SIGN_OUT: '1b780a68-502f-4ccc-aa90-81266d7216cd'
            welsh:
              SAVE_SIGN_OUT: '1b780a68-502f-4ccc-aa90-81266d7216cd'
