spring:
  application:
    name: NFDIV Case API Functional Tests
# because functional tests load up SpringBootTest
azure:
  application-insights:
    instrumentation-key: functional-test

test-url: ${TEST_URL:http://localhost:4013}
