spring:
  application:
    name: NFDIV Case API Functional Tests
# because functional tests load up SpringBootTest
azure:
  application-insights:
    instrumentation-key: functional-test

test-url: ${TEST_URL:http://localhost:4013}

uk:
  gov:
    notify:
      api:
        key: dummy
        baseUrl: https://api.notifications.service.gov.uk

s2s-url: ${TEST_S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
s2s-name: ${TEST_S2S_NAME:ccd_data}
s2s-secret: ${CCD_DATA_STORE_S2S_SECRET:}
