name: Version type definitions

on:
  push:
    branches:
      - master
  pull_request:
      branches:
          - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
        working-directory: ./ccd-definitions

  bump-version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          PACKAGEJSON_DIR: './ccd-definitions'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
